version: "3"
services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 3000:3000

volumes: 
  db: ~
